version: '2'
services:
  web:
    image: buddyingdevelopment/php:7.0-apache
    container_name: starter-web
    depends_on:
      - db
      - smtp
    ports:
      - "80:80"
    volumes:
      - ./config/vhosts.conf:/etc/httpd/conf.d/vhosts.conf
      - ../public:/var/www/html
      - ./config/wp-config.php:/var/www/html/wp-config.php
    environment:
      PHP_XDEBUG: 'off'
    working_dir: /var/www/html

  db:
    image: buddyingdevelopment/mysql:5.6
    container_name: starter-db
    ports:
      - "3306:3306"
    volumes:
      - ./.db:/var/lib/mysql
      - ./config/wordpress_dump.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: starter_db
      MYSQL_USER: starter_user
      MYSQL_PASSWORD: passw0rd

  smtp:
    image: schickling/mailcatcher
    container_name: starter-smtp
    ports:
      - "1080:1080"
      - "1025:1025"