version: '2'
services:
  sample-wordpress-db:
    image: buddyingdevelopment/mysql:5.6
    container_name: sample-wordpress-db
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
      - ./localhost.latest.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: passw0rd

  sample-wordpress-web:
    image: buddyingdevelopment/php:7.0-apache
    container_name: sample-wordpress-web
    depends_on:
      - sample-wordpress-db
    ports:
      - "80:80"
    volumes:
      - ./config/vhosts.conf:/etc/httpd/conf.d/vhosts.conf
      - ../wordpress:/var/www/html
      - ./config/wp-config.php:/var/www/html/wp-config.php
    environment:
      PHP_XDEBUG: 'off'
